apiVersion: v1
kind: Secret
metadata:
  name: flightctl-ui
  namespace: {{ .Values.flightctlUi.namespace }}
type: Opaque
stringData:
  BASE_UI_URL: {{ .Values.flightctlUi.baseUiUrl | quote }}
  INTERNAL_OIDC_URL: {{ .Values.flightctlUi.internalOidcUrl | quote }}
  FLIGHTCTL_SERVER: {{ .Values.flightctlUi.flightctlServer | quote }}
  FLIGHTCTL_METRICS_SERVER: {{ .Values.flightctlUi.flightctlMetricsServer | quote }}
  FLIGHTCTL_GRPC_SERVER: {{ .Values.flightctlUi.flightctlGrpcServer | quote }}
  PORT: "8080"
  BOOTC_IMG_URL: {{ .Values.flightctlUi.bootcImgUrl }}
  QCOW2_IMG_URL: {{ .Values.flightctlUi.qcow2ImgUrl }}