apiVersion: v1
kind: Secret
metadata:
  name: flightctl-ui
  namespace: {{ .Values.flightctlUi.namespace }}
type: Opaque
stringData:
  KEYCLOAK_AUTHORITY: {{ .Values.keycloak.authority | quote }}
  KEYCLOAK_CLIENTID: {{ .Values.keycloak.clientid | quote }}
  KEYCLOAK_REDIRECT: {{ .Values.keycloak.redirect | quote }}
  KEYCLOAK_SECRET: {{ .Values.keycloak.secret | quote }}
  FLIGHTCTL_SERVER: {{ .Values.flightctlUi.flightctlServer | quote }}
  FLIGHTCTL_METRICS_SERVER: {{ .Values.flightctlUi.flightctlMetricsServer | quote }}
  FLIGHTCTL_GRPC_SERVER: {{ .Values.flightctlUi.flightctlGrpcServer | quote }}
  PORT: "8080"
  BOOTC_IMG_URL: {{ .Values.flightctlUi.bootcImgUrl }}
  QCOW2_IMG_URL: {{ .Values.flightctlUi.qcow2ImgUrl }}