/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export type { ApplicationsSummaryStatus } from './models/ApplicationsSummaryStatus';
export { ApplicationsSummaryStatusType } from './models/ApplicationsSummaryStatusType';
export type { ApplicationStatus } from './models/ApplicationStatus';
export { ApplicationStatusType } from './models/ApplicationStatusType';
export type { Condition } from './models/Condition';
export { ConditionStatus } from './models/ConditionStatus';
export { ConditionType } from './models/ConditionType';
export type { Device } from './models/Device';
export type { DeviceApplicationsStatus } from './models/DeviceApplicationsStatus';
export type { DeviceConfigStatus } from './models/DeviceConfigStatus';
export type { DeviceIntegrityStatus } from './models/DeviceIntegrityStatus';
export type { DeviceIntegrityStatusSummary } from './models/DeviceIntegrityStatusSummary';
export { DeviceIntegrityStatusSummaryType } from './models/DeviceIntegrityStatusSummaryType';
export type { DeviceList } from './models/DeviceList';
export type { DeviceOSSpec } from './models/DeviceOSSpec';
export type { DeviceOSStatus } from './models/DeviceOSStatus';
export type { DeviceResourceStatus } from './models/DeviceResourceStatus';
export { DeviceResourceStatusType } from './models/DeviceResourceStatusType';
export type { DeviceSpec } from './models/DeviceSpec';
export type { DeviceStatus } from './models/DeviceStatus';
export type { DeviceSummaryStatus } from './models/DeviceSummaryStatus';
export { DeviceSummaryStatusType } from './models/DeviceSummaryStatusType';
export type { DeviceSystemInfo } from './models/DeviceSystemInfo';
export type { DeviceUpdatedStatus } from './models/DeviceUpdatedStatus';
export { DeviceUpdatedStatusType } from './models/DeviceUpdatedStatusType';
export type { EnrollmentRequest } from './models/EnrollmentRequest';
export type { EnrollmentRequestApproval } from './models/EnrollmentRequestApproval';
export type { EnrollmentRequestList } from './models/EnrollmentRequestList';
export type { EnrollmentRequestSpec } from './models/EnrollmentRequestSpec';
export type { EnrollmentRequestStatus } from './models/EnrollmentRequestStatus';
export type { Error } from './models/Error';
export type { Fleet } from './models/Fleet';
export type { FleetList } from './models/FleetList';
export type { FleetSpec } from './models/FleetSpec';
export type { FleetStatus } from './models/FleetStatus';
export type { GenericConfigSpec } from './models/GenericConfigSpec';
export type { GitConfigProviderSpec } from './models/GitConfigProviderSpec';
export type { GitGenericRepoSpec } from './models/GitGenericRepoSpec';
export type { GitHttpConfig } from './models/GitHttpConfig';
export type { GitHttpRepoSpec } from './models/GitHttpRepoSpec';
export type { GitSshConfig } from './models/GitSshConfig';
export type { GitSshRepoSpec } from './models/GitSshRepoSpec';
export type { InlineConfigProviderSpec } from './models/InlineConfigProviderSpec';
export type { KubernetesSecretProviderSpec } from './models/KubernetesSecretProviderSpec';
export type { LabelSelector } from './models/LabelSelector';
export type { ListMeta } from './models/ListMeta';
export type { ObjectMeta } from './models/ObjectMeta';
export type { PatchRequest } from './models/PatchRequest';
export type { RenderedDeviceSpec } from './models/RenderedDeviceSpec';
export type { Repository } from './models/Repository';
export type { RepositoryList } from './models/RepositoryList';
export type { RepositorySpec } from './models/RepositorySpec';
export type { RepositoryStatus } from './models/RepositoryStatus';
export type { ResourceSync } from './models/ResourceSync';
export type { ResourceSyncList } from './models/ResourceSyncList';
export type { ResourceSyncSpec } from './models/ResourceSyncSpec';
export type { ResourceSyncStatus } from './models/ResourceSyncStatus';
export type { Status } from './models/Status';
export { TemplateDiscriminators } from './models/TemplateDiscriminators';
export type { TemplateVersion } from './models/TemplateVersion';
export type { TemplateVersionList } from './models/TemplateVersionList';
export type { TemplateVersionSpec } from './models/TemplateVersionSpec';
export type { TemplateVersionStatus } from './models/TemplateVersionStatus';
