const APP_TITLE = 'Edge Manager';
const API_VERSION = 'v1beta1';
const PAGE_SIZE = 15;
const EVENT_PAGE_SIZE = 200; // It's 500 in OCP console
const CERTIFICATE_VALIDITY_IN_YEARS = 1;

export { APP_TITLE, API_VERSION, PAGE_SIZE, EVENT_PAGE_SIZE, CERTIFICATE_VALIDITY_IN_YEARS };
