{{ if ((.Values.global).baseDomainTls).cert }}
apiVersion: v1
kind: Secret
metadata:
  name: flightctl-ui-serving-cert
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  tls.crt: {{ .Values.global.baseDomainTls.cert | quote }}
  tls.key: {{ .Values.global.baseDomainTls.key | quote }}
{{ end }}
