apiVersion: v1
kind: Secret
metadata:
  name: flightctl-ui-certs
  namespace: {{ .Values.flightctlUi.namespace }}
type: Opaque
stringData:
  ca.crt: {{ .Values.flightctlUi.certs.ca | quote }}
  front-cli.crt: {{ .Values.flightctlUi.certs.frontClicrt | quote }}
  front-cli.key: {{ .Values.flightctlUi.certs.frontClikey | quote }}
  api-sig.key: {{ .Values.flightctlUi.certs.apiSigkey | quote }}
