apiVersion: v1
kind: Secret
metadata:
  name: flightctl-ui
  namespace: {{ .Values.flightctlUi.namespace }}
type: Opaque
stringData:
  FLIGHTCTL_SERVER: {{ .Values.flightctlUi.flightctlServer | quote }}
  FLIGHTCTL_METRICS_SERVER: {{ .Values.flightctlUi.flightctlMetricsServer | quote }}
